language: bash

services:
- docker

env:
  global:
  - BASE_IMAGE_STABILITY_TAG=4.16.3
  - WEBGRIND_VER=1.7.0 TAGS=1.7,1,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
